### ISSUE TITLE
使用报错：TypeError: Cannot create property 'startTime' on number '3'

### ISSUE THREAD

**Issue by roark47** [JacksonTian/httpx#12]
Hi, JacksonTian:

我在使用阿里云 @alicloud/pop-core 包时遇到以下报错信息，错误来源您的 npm 包 httpx：

```
TypeError: Cannot create property 'startTime' on number '3'

      at startResponseTimer (node_modules/httpx/lib/index.js:119:23)
      at TLSSocket.<anonymous> (node_modules/httpx/lib/index.js:153:11)
```

此错误来源您的代码第 119 行，您在此试图向一个数字类型 timer 设置属性，这种行为在严格模式下是被禁止的，我已修复此 Bug 并提交 PR，请接收，谢谢。

**Comment by peze** [comment]
你这边这个是前端的settimeout有这个问题，httpx主要是在node后端使用的。:)

**Comment by idododu** [comment]
同样问题，我这儿是node后端使用的
