### ISSUE TITLE
use jest get TypeError: Cannot create property 'startTime' on number '3'

### ISSUE THREAD

**Issue by shynome** [JacksonTian/httpx#9]
https://github.com/JacksonTian/httpx/blob/e031c7341c85160565973a179b20f511149c349d/lib/index.js#L119
```
TypeError: Cannot create property 'startTime' on number '3'

      at startResponseTimer (node_modules/httpx/lib/index.js:119:23)
      at TLSSocket.<anonymous> (node_modules/httpx/lib/index.js:141:11)
```

**Comment by shynome** [comment]
testEnvironment 默认是 jsdom , 改成 node 就行了
